Repository jiro4989/pnm, pull requests merged in 2021-01, with the labels that each got.

#6 Use GitHub Actions #5
  .github/pr-labeler.yml
  .github/workflows/docs.yml
  .github/workflows/pr-labeler.yml
  .github/workflows/test.yml
  .travis.yml
Labels: chore

#4 🔥 最大輝度を指定するように修正
  src/pnm.nim
  tests/tpnm.nim
Labels: feature

#10 fix: broken runnableExamples #9
  .github/workflows/test.yml
  src/pnm.nim
Labels: bug
